export const LOCAL_SCHEMA_TABLES = [
  'stores',
  'inventory_items',
  'customers',
  'transactions',
  'transaction_items',
  'inventory_movements',
  'utang_entries',
  'sync_events',
  'assistant_interactions',
] as const;

export function getCreateTableStatements() {
  return [
    `create table if not exists stores (
      id text primary key,
      owner_user_id text not null,
      name text not null,
      currency_code text not null default 'PHP',
      timezone text not null default 'Asia/Manila',
      metadata_json text not null default '{}',
      created_at text not null default (datetime('now')),
      updated_at text not null
    )`,
    `create table if not exists inventory_items (
      id text primary key,
      store_id text not null,
      sku text,
      name text not null,
      description text,
      category text,
      unit text not null default 'pcs',
      aliases_json text not null default '[]',
      price real not null default 0,
      cost real,
      current_stock real not null default 0,
      low_stock_threshold real not null default 0,
      is_active integer not null default 1,
      archived_at text,
      metadata_json text not null default '{}',
      created_at text not null default (datetime('now')),
      updated_at text not null,
      foreign key (store_id) references stores(id) on delete cascade
    )`,
    `create table if not exists customers (
      id text primary key,
      store_id text not null,
      name text not null,
      aliases_json text not null default '[]',
      phone text,
      utang_balance real not null default 0,
      is_active integer not null default 1,
      archived_at text,
      metadata_json text not null default '{}',
      created_at text not null default (datetime('now')),
      updated_at text not null,
      foreign key (store_id) references stores(id) on delete cascade
    )`,
    `create table if not exists transactions (
      id text primary key,
      store_id text not null,
      client_mutation_id text not null,
      raw_text text not null,
      source text not null default 'voice',
      sync_status text not null default 'pending',
      parser_source text not null default 'offline_rule_parser',
      local_parse_json text,
      gemini_verification_json text,
      is_utang integer not null default 0,
      customer_id text,
      created_at text not null default (datetime('now')),
      synced_at text,
      foreign key (store_id) references stores(id) on delete cascade,
      foreign key (customer_id) references customers(id),
      unique (store_id, client_mutation_id)
    )`,
    `create table if not exists transaction_items (
      id text primary key,
      transaction_id text not null,
      store_id text not null,
      item_id text not null,
      quantity_delta real not null,
      unit_price real not null default 0,
      line_total real not null default 0,
      local_parse_json text,
      created_at text not null default (datetime('now')),
      foreign key (transaction_id) references transactions(id) on delete cascade,
      foreign key (store_id) references stores(id) on delete cascade,
      foreign key (item_id) references inventory_items(id)
    )`,
    `create table if not exists inventory_movements (
      id text primary key,
      store_id text not null,
      item_id text not null,
      transaction_id text,
      movement_type text not null,
      quantity_delta real not null,
      client_mutation_id text not null,
      note text,
      created_at text not null default (datetime('now')),
      foreign key (store_id) references stores(id) on delete cascade,
      foreign key (item_id) references inventory_items(id),
      foreign key (transaction_id) references transactions(id)
    )`,
    `create table if not exists utang_entries (
      id text primary key,
      store_id text not null,
      customer_id text not null,
      transaction_id text,
      entry_type text not null,
      amount real not null,
      note text,
      client_mutation_id text not null,
      created_at text not null default (datetime('now')),
      foreign key (store_id) references stores(id) on delete cascade,
      foreign key (customer_id) references customers(id),
      foreign key (transaction_id) references transactions(id)
    )`,
    `create table if not exists sync_events (
      id text primary key,
      store_id text not null,
      transaction_id text,
      status text not null default 'pending',
      request_json text,
      response_json text,
      error_message text,
      created_at text not null default (datetime('now')),
      foreign key (store_id) references stores(id) on delete cascade,
      foreign key (transaction_id) references transactions(id)
    )`,
    `create table if not exists assistant_interactions (
      id text primary key,
      store_id text not null,
      client_interaction_id text not null,
      question_text text not null,
      answer_text text,
      spoken_text text,
      input_mode text not null default 'text',
      status text not null default 'pending',
      created_at text not null default (datetime('now')),
      synced_at text,
      foreign key (store_id) references stores(id) on delete cascade,
      unique (store_id, client_interaction_id)
    )`,
  ];
}

export const LOCAL_INDEX_STATEMENTS = [
  `create index if not exists inventory_items_store_idx on inventory_items (store_id)`,
  `create index if not exists customers_store_idx on customers (store_id)`,
  `create index if not exists transactions_store_sync_status_idx on transactions (store_id, sync_status)`,
  `create index if not exists inventory_movements_store_item_idx on inventory_movements (store_id, item_id)`,
  `create index if not exists utang_entries_store_customer_idx on utang_entries (store_id, customer_id)`,
];
